#
# PROGRAM: Assignment 7
# AUTHOR:  Francisco Banda
#

server client: client.cpp server.cpp
	g++ -g -ansi -pedantic -Wall -Werror -std=c++14 client.cpp -o client
	g++ -g -ansi -pedantic -Wall -Werror -std=c++14 server.cpp -o server

clean:
	rm -f *.o client server